ninachanteau/wandr

app/controllers/trips_controller.rb
app/models/trip.rb
app/models/user.rb
app/views/shared/_card.html.erb
app/views/trips/index.html.erb

method index
view indew basique

base view for index trip

---

app/controllers/trips_controller.rb
app/models/user.rb
app/views/trips/new.html.erb

J'ai créé les méthodes new et create pour les trips et la view du form pour un new trip.

Form create trip

---

Gemfile
Gemfile.lock
app/controllers/transportations_controller.rb
app/models/user.rb
app/views/transportations/index.html.erb
db/seeds.rb

Transportation index created but not tested yet (waiting to create seed tomorrow)

Create transportation index

---

app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_wrapper.scss
app/assets/stylesheets/layouts/_index.scss
app/views/layouts/application.html.erb

wrapper light-gray sur le layout (on pourra le changer en blanc)

add a wrapper in the layout

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_wrapper.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_trips-new.scss
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/trips/new.html.erb

J'ai mis un footer similaire à celui d'AirJam qui apparaît en bas du wrapper quelle que soit la taille du contenu de la page.

add a footer

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_navbar.scss
app/controllers/accommodations_controller.rb
app/controllers/activities_controller.rb
app/controllers/restaurants_controller.rb
app/controllers/trips_controller.rb
app/javascript/components/form_url.js
app/javascript/packs/application.js
app/models/accommodation.rb
app/models/activity.rb
app/models/restaurant.rb
app/views/accommodations/create.js.erb
app/views/accommodations/edit.html.erb
app/views/activities/edit.html.erb
app/views/layouts/application.html.erb
app/views/restaurants/edit.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/urlForms.js.erb
config/application.rb
config/routes.rb
db/seeds.rb

create and edit element through url in navbar done
No ajax yet
No style yet

Edit new url

---

app/controllers/trips_controller.rb
app/views/shared/_card.html.erb
app/views/trips/show.html.erb
db/seeds.rb

seed and link to show

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/transportations_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/transportations/index.html.erb
db/seeds.rb

Transportation index now works - CSS and "edit status" function to be added in another branch

Testing transpo index

---

app/assets/stylesheets/components/_navbar.scss
app/controllers/transportations_controller.rb
app/views/layouts/application.html.erb
app/views/shared/_footer.html.erb
app/views/shared/_navbar.html.erb
app/views/transportations/index.html.erb
db/seeds.rb

Avatar in navbar changed to current_user instead of ssaunier

Avatar navbar

---

app/controllers/transportations_controller.rb
app/views/transportations/index.html.erb
config/routes.rb

edit status buttons added to transpo index

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/components/_wrapper.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/shared/_sidebar.html.erb

la navbar est ok
l'avatar avec dropdown-menu est dans la sidebar

Navbar design

---

app/controllers/participations_controller.rb
app/controllers/trips_controller.rb
app/views/trips/show.html.erb
config/routes.rb

Adding participations to trip on trip#show
handles both user participant and non-user participants

adding participations to trip done

---

app/assets/stylesheets/components/_wrapper.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

forms to log-in or sign-up are centered and responsive

center and responsive login/signin forms

---

app/controllers/transportations_controller.rb
app/javascript/plugins/flatpickr.js
app/views/layouts/application.html.erb
app/views/transportations/index.html.erb
app/views/transportations/new.html.erb

"New", "Create", "Destroy"created for transportation

New transportation

---

app/controllers/accommodations_controller.rb
app/controllers/activities_controller.rb
app/controllers/restaurants_controller.rb
app/views/accommodations/index.html.erb
app/views/activities/index.html.erb
app/views/restaurants/index.html.erb
config/routes.rb

Index method/route/view created for resto, accom, activity.
No content.

index created for resto, accom, activity

---

app/controllers/restaurants_controller.rb
app/models/accommodation.rb
app/models/activity.rb
app/models/restaurant.rb
app/models/transportation.rb

methods add_participant(participant) and count_participants working and taking into account subtleties
to be adjusted for use

done and checked in console for restaurants

---

app/assets/stylesheets/components/_wrapper.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/config/_fonts.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_restaurants-new.scss
app/assets/stylesheets/pages/_trips-index.scss
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/restaurants/edit.html.erb
app/views/transportations/index.html.erb
app/views/trips/index.html.erb

j'ai modifié le wrapper + les fonts + les couleurs
pour les couleurs j'ai laissé les anciennes au cas où pour éviter les bugs mais il faut maintenant utiliser principalement : 
$gray => texte
$middle-gray
$light-gray
$white-transparent => fonds
$white-middle-transparent => hover
$yellow
$middle-yellow
$light-yellow
et pour les boutons si besoin : btn btn-info qui reprend le bon jaune

layout and colors

---

app/controllers/accommodations_controller.rb
app/controllers/activities_controller.rb
app/controllers/restaurants_controller.rb

ca ne bug plus si ca ne trouve pas un des éléments.

added ifs in scraping

---

Gemfile.lock
app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/components/_wrapper.scss
app/assets/stylesheets/config/_colors.scss
app/assets/stylesheets/layouts/_index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_transportations-index.scss
app/views/accommodations/index.html.erb
app/views/activities/index.html.erb
app/views/restaurants/index.html.erb
app/views/transportations/index.html.erb

voilà le début du design de l'index des transports !

transportation index

---

app/controllers/accommodations_controller.rb
app/controllers/activities_controller.rb
app/controllers/restaurants_controller.rb
app/views/accommodations/edit.html.erb
app/views/activities/edit.html.erb
app/views/restaurants/edit.html.erb
app/views/shared/_sidebar.html.erb

done
undertaking migration to improve it

Add trip to restaurant in edit

---

app/controllers/trips_controller.rb
app/javascript/components/autocomplete.js
app/models/transportation.rb
app/views/trips/show.html.erb
db/migrate/20180321121231_add_coordinates_to_transportations.rb
db/schema.rb
db/seeds.rb

change seed
debut de calendar
geocoding for transportation
les ports sont des addresses

seed and map for transport

---

app/assets/stylesheets/pages/_accommodations-index.scss
app/assets/stylesheets/pages/_activities-index.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_restaurants-index.scss
app/assets/stylesheets/pages/_transportations-index.scss
app/views/accommodations/index.html.erb
app/views/activities/index.html.erb
app/views/restaurants/index.html.erb

Les designs des pages index pour transportations, accommodations and activities sont faits ! à remplir et on peut bien sûr modifier le contenu (ou le nombre) des box

Index views

---

app/controllers/accommodations_controller.rb
app/controllers/trips_controller.rb
app/views/accommodations/edit.html.erb
app/views/accommodations/index.html.erb
app/views/activities/index.html.erb
app/views/restaurants/index.html.erb
app/views/shared/_sidebar.html.erb
app/views/transportations/index.html.erb

Index done mais sans test car pas de données à afficher (need more seed)

index for resto accom activity

---

app/models/accommodation.rb
app/models/activity.rb
app/models/restaurant.rb
app/models/transportation.rb
app/views/accommodations/index.html.erb
app/views/activities/index.html.erb
app/views/restaurants/index.html.erb
app/views/transportations/index.html.erb

Few adjustments

---

app/controllers/restaurants_controller.rb
app/controllers/transportations_controller.rb
app/javascript/plugins/flatpickr.js
app/views/restaurants/new.html.erb
app/views/transportations/new.html.erb

"New" resto

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_colors.scss

les modifs d'hier pas pushées... j'ai mis les couleurs en hexadécimal pour que ce soit plus facile à utiliser sur la map

colors in hexadecimal

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_trips-index.scss
app/views/trips/index.html.erb

trips index design

---

app/assets/stylesheets/pages/_trips-show.scss
app/views/shared/_navbar.html.erb
app/views/trips/show.html.erb

add participant modal

---

app/controllers/accommodations_controller.rb
app/javascript/plugins/flatpickr.js
app/views/accommodations/index.html.erb
app/views/accommodations/new.html.erb

accommodation new + index

---

app/controllers/restaurants_controller.rb
app/views/restaurants/index.html.erb

restaurant modal

---

app/controllers/restaurants_controller.rb
app/javascript/packs/map.js
app/models/restaurant.rb
app/views/accommodations/_map_box_booked.html.erb
app/views/accommodations/_map_box_wishlist.html.erb
app/views/activities/_map_box_booked.html.erb
app/views/activities/_map_box_wishlist.html.erb
app/views/restaurants/_map_box_booked.html.erb
app/views/restaurants/_map_box_wishlist.html.erb
app/views/restaurants/index.html.erb
app/views/transportations/_map_box_arrival.html.erb
app/views/transportations/_map_box_departure.html.erb
app/views/transportations/index.html.erb
db/migrate/20180322164209_change_columns_from_restaurants.rb
db/schema.rb
db/seeds.rb

migration restaurants avec tous les changements partout qui vont avec et style map

migration restaurant and style map

---

app/assets/stylesheets/components/_sidebar.scss
app/controllers/activities_controller.rb
app/views/activities/index.html.erb
app/views/shared/_sidebar.html.erb

modal new activity ok + new icon

activities modal and icon

---

app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_trips-index.scss

l'autocomplete apparaît au-dessus des  modals !

Bug fixing elsa

---

app/views/accommodations/index.html.erb
app/views/activities/index.html.erb
app/views/restaurants/index.html.erb
app/views/shared/_delete-icon.html.erb
app/views/transportations/index.html.erb
app/views/trips/index.html.erb

Icons added to transpo update
transpo ordered by date
titles changed

status on transpo update

---

app/views/activities/index.html.erb
app/views/restaurants/index.html.erb

Resto wishlist update with icons
Activity wishlist fixed

Resto wishlist

---

app/views/accommodations/index.html.erb
app/views/transportations/index.html.erb

prices corrected with .00 and euro sign on one line

price corrected

---

app/controllers/accommodations_controller.rb
app/controllers/trips/navbar_accommodations_controller.rb
app/controllers/trips/navbar_activities_controller.rb
app/controllers/trips/navbar_restaurants_controller.rb
app/models/trip.rb
app/views/accommodations/edit.html.erb
app/views/accommodations/index.html.erb

quick add working now (visible in trip where it was added)
removed number of nights from accommodation modal

Fix acco participants

---

app/assets/stylesheets/pages/_transportations-index.scss
app/views/transportations/index.html.erb

Transportation card

---

app/assets/stylesheets/pages/_restaurants-index.scss
app/assets/stylesheets/pages/_transportations-index.scss
app/views/restaurants/index.html.erb

first step of cards on restaurant index

Restaurant index

---

app/assets/stylesheets/components/_sidebar.scss
app/controllers/accommodations_controller.rb
app/controllers/activities_controller.rb
app/controllers/restaurants_controller.rb
app/controllers/sessions/sessions_controller.rb
app/controllers/transportations_controller.rb
app/models/user.rb
app/views/accommodations/index.js.erb
app/views/activities/index.js.erb
app/views/shared/_sidebar.html.erb
app/views/transportations/index.js.erb

Notifications coded - à reprendre pour finaliser session cookie quand on aura avancé

Ajax notif

---

app/assets/stylesheets/pages/_accommodations-index.scss
app/controllers/trips_controller.rb
app/views/trips/_show.html.erb

photo positioning
j'ai revu le link du pdf pour pas etre rediriger vers la page mais vers le telechargement du pdf direct

photo and pdf link

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_trips-index.scss
app/assets/stylesheets/pages/_trips-show.scss
app/views/accommodations/_index.html.erb
app/views/accommodations/index.js.erb
app/views/activities/_index.html.erb
app/views/activities/index.js.erb
app/views/restaurants/index.js.erb
app/views/shared/_navbar.html.erb
app/views/shared/_navbar_title.html.erb
app/views/transportations/index.js.erb
app/views/trips/_index.html.erb
app/views/trips/_show.html.erb

navbar ajax

---

app/assets/stylesheets/components/_navbar.scss
app/views/accommodations/index.js.erb
app/views/shared/_navbar.html.erb

Formattage navbar en place pour la démo!

Navbar formatting

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/pages/_trips-index.scss
app/views/shared/_card.html.erb
app/views/trips/_index.html.erb

cards, colors and alignment on trips index

trips index

---

app/assets/stylesheets/pages/_accommodations-index.scss
app/assets/stylesheets/pages/_activities-index.scss
app/assets/stylesheets/pages/_restaurants-index.scss
app/assets/stylesheets/pages/_transportations-index.scss
app/assets/stylesheets/pages/_trips-show.scss
app/views/accommodations/_index.html.erb
app/views/activities/_index.html.erb
app/views/restaurants/_index.html.erb
app/views/transportations/_index.html.erb
app/views/trips/_show.html.erb

divs align, margin, padding
titles out

Tabls style

---

app/assets/stylesheets/pages/_trips-show.scss
app/views/trips/_show.html.erb

New transparent div added to trip show

New div trip show

---

app/views/shared/_navbar.html.erb

quick add now aligned on the right when activity is chosen in the dropdown menu

navbar quick add formatting issue fixed

---

app/models/user.rb

Nouvelle logique notification qui devrait n'afficher qu'une notif au lieu du nombre de participants d'un nouvel item. A tester par Nina dans le scénario de la demo

notifications new logic - please test online

---

app/models/user.rb

Notifications disabled - new_count function returns 0

notifications disabled

---

app/views/trips/navbar_accommodations/_edit_form.html.erb
app/views/trips/navbar_activities/_edit_form.html.erb
app/views/trips/navbar_restaurants/_edit_form.html.erb

mettre save au lieu de update dans le quick add form

---

app/controllers/activities_controller.rb
app/controllers/trips_controller.rb
app/models/user.rb
app/views/shared/_sidebar.html.erb

notifications améliorées mais non fonctionnelles pour la demo

notifications abandoned

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_accommodations-index.scss
app/assets/stylesheets/pages/_activities-index.scss
app/assets/stylesheets/pages/_restaurants-index.scss
app/assets/stylesheets/pages/_transportations-index.scss
app/assets/stylesheets/pages/_trips-index.scss
app/assets/stylesheets/pages/_trips-show.scss
app/views/accommodations/_index.html.erb
app/views/activities/_index.html.erb
app/views/layouts/application.html.erb
app/views/restaurants/_index.html.erb
app/views/shared/_sidebar.html.erb
app/views/transportations/_index.html.erb
app/views/trips/_index.html.erb
app/views/trips/_show.html.erb

Cards and design

---

app/views/activities/_index.html.erb

photo activity

---

app/assets/stylesheets/components/_sidebar.scss
app/assets/stylesheets/pages/_trips-show.scss
app/views/shared/_sidebar.html.erb
app/views/trips/_show.html.erb

Bug fixing last day

---

app/views/shared/_navbar.html.erb
app/views/shared/_navbar_title.html.erb
app/views/trips/navbar_restaurants/_update_form.html.erb

changed title of navbar and button save of restaurant

Ajaxify status
